version: "3"
services:

  ms-email-db:
    image: postgres:16
    container_name: ms-email-db
    restart: always
    environment:
      - POSTGRES_DB=ms-email-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432